name: weh
description: An absolute bare-bones web app.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=2.19.6 <3.0.0"
dependencies:
  vector_math: "^2.1.4"
  chronosgl: ">=4.0.2"

dev_dependencies:
  build_runner: ^2.4.5
  build_web_compilers: ^4.0.3
  lints: ^2.0.0
